# Capstone 2: Business Analysis with Python

## EmporiUm Sales Analysis

### This project will show analysis for thesSouth region with the teritorries of Florida and Texas using python and python functions like Pandas, Matplotlib and NumPy
* ##### The manager for Florida is Lana Ilana with stores 719-729
* ##### The manager for Texas is Jeff "Howdy" Richards with store 901-911

The analysis will show: 
* Monthly sales trends over time
* Ranking of store performance
* Analysis of customer buying behavior
* Evaluation of product category performance
* Data-driven marketing strategies

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
StoreDetail = pd.read_csv('StoreDetail.csv')

In [5]:
StoreDetail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [6]:
StoreDetail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

In [10]:
StoreSales = pd.read_csv('StoreSales.csv')

In [11]:
StoreSales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [12]:
StoreSales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

In [14]:
Products = pd.read_csv('Products.csv')

In [15]:
Products.head()

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [16]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

In [17]:
ProductCat = pd.read_csv('ProductCategories.csv')

In [18]:
ProductCat.head()

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [19]:
ProductCat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

In [21]:
CustList = pd.read_csv('customer_list.csv')

In [22]:
CustList.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [23]:
CustList.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

#  Core Marketing Analysis

#### Identify territory managers, store IDs, and store locations for each assigned territory.

In [55]:
South = StoreDetail[(StoreDetail['State'] == 'Texas') | (StoreDetail['State'] == 'Florida')]  
South
# The manager for Florida is Lana Ilana with stores 719-729
# The manager for Texas is Jeff "Howdy" Richards with store 901-911

,Store Location,State,Store ID,Territory Manager,Region,Region Director
26,Cape Canaveral,Florida,719,Lana Ilana,South,Andy Gisselquist
27,Fort Lauderdale,Florida,720,Lana Ilana,South,Andy Gisselquist
28,Jacksonville,Florida,721,Lana Ilana,South,Andy Gisselquist
29,Key West,Florida,722,Lana Ilana,South,Andy Gisselquist
30,Lakeland,Florida,723,Lana Ilana,South,Andy Gisselquist
31,Miami,Florida,724,Lana Ilana,South,Andy Gisselquist
32,Naples,Florida,725,Lana Ilana,South,Andy Gisselquist
33,Orlando,Florida,726,Lana Ilana,South,Andy Gisselquist
34,Sebring,Florida,727,Lana Ilana,South,Andy Gisselquist
35,Tallahassee,Florida,728,Lana Ilana,South,Andy Gisselquist
36,Tampa,Florida,729,Lana Ilana,South,Andy Gisselquist
100,Arlington,Texas,901,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
101,Austin,Texas,902,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
102,Bacliff,Texas,903,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
103,Baytown,Texas,904,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
104,Beaumont,Texas,905,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
105,Cedar Park,Texas,906,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
106,Dallas,Texas,907,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
107,Denton,Texas,908,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
108,Desoto,Texas,909,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
109,Fort Worth,Texas,910,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
110,Georgetown,Texas,911,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

#### Monthly total revenue for in-store sales in each of the two sales territories, over the full period covered by the data

In [64]:
SouthMonthly = StoreSales[(StoreSales['Store ID'] >= 719)] #| (StoreDetail['State'] == 'Florida')]  
SouthMonthly

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
23             1/1/2022       719        NaN   105376-M        44.50
24             1/1/2022       721        NaN  105310-IT        71.74
25             1/1/2022       723        NaN   105377-A         5.00
26             1/1/2022       723        NaN   105378-T       155.60
27             1/1/2022       724        NaN   105379-A        28.00
...                 ...       ...        ...        ...          ...
335124       12/31/2025       909        NaN   105353-A        20.36
335125       12/31/2025       909      332.0   105364-S        17.70
335126       12/31/2025       910        NaN   105672-B        26.52
335127       12/31/2025       910        NaN   105653-M        11.00
335128       12/31/2025       910        NaN  105300-IT        77.81

[288631 rows x 5 columns]