## Capstone 2 Bonus Analysis

### These are bonus analysis qurestion that I was given

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
StoreDetail = pd.read_csv('StoreDetail.csv') # importing data csv

In [3]:
StoreSales = pd.read_csv('StoreSales.csv') # importing data csv

In [4]:
Products = pd.read_csv('Products.csv') # importing data csv

In [5]:
ProductCat = pd.read_csv('ProductCategories.csv') # importing data csv

In [6]:
CustList = pd.read_csv('customer_list.csv') # importing data csv

### Filtering, Sorting & Exploration

#### Create a list of all transactions from January 2024, sorted by sale amount from highest to lowest. Which transactions had a sale amount greater than $500?

In [7]:
StoreSales['Transaction Date'] = pd.to_datetime(StoreSales['Transaction Date'])
jan_data = StoreSales[(StoreSales['Transaction Date'] >= '2024-01-01') &(StoreSales['Transaction Date'] < '2024-02-01')
]

sorted_data = jan_data.sort_values(by='Sale Amount', ascending=False)
sorted_data

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139643       2024-01-31       736        NaN   105444-S          2.4
133337       2024-01-01       901      324.0   105402-S          2.4
138904       2024-01-27       850        NaN   105611-S          2.4
136726       2024-01-17       739        NaN   105444-S          2.4
138912       2024-01-27       853        NaN   105821-S          2.4

[6654 rows x 5 columns]

In [8]:
above_500 = sorted_data[sorted_data['Sale Amount'] > 500]
above_500

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139274       2024-01-29       815        NaN  105262-IT        603.5
139391       2024-01-30       718        NaN  105262-IT        603.5
136360       2024-01-15       847        NaN  105262-IT        603.5
134154       2024-01-05       825        NaN  105262-IT        603.5
136218       2024-01-15       728        NaN  105262-IT        603.5

[497 rows x 5 columns]

#### Find all products whose product number begins with 10525. What category and subcategory do they belong to?

In [9]:
ProdNumCat = Products.merge(ProductCat, on='CategoryID')
ProdNumCat = ProdNumCat[ProdNumCat['Prod Num'].str.startswith('10525')]
ProdCat = ProdNumCat[['Prod Num', 'Category', 'Subcategory']]
ProdCat

     Prod Num                  Category                  Subcategory
14  105250-IT  Technology & Accessories                      Tablets
15  105250-IT  Technology & Accessories                  Calculators
16  105250-IT  Technology & Accessories            Software Download
17  105250-IT  Technology & Accessories                   Headphones
18  105250-IT  Technology & Accessories         External Accessories
..        ...                       ...                          ...
79  105259-IT  Technology & Accessories            Software Download
80  105259-IT  Technology & Accessories                   Headphones
81  105259-IT  Technology & Accessories         External Accessories
82  105259-IT  Technology & Accessories  Chargers and Power Adapters
83  105259-IT  Technology & Accessories                      Laptops

[70 rows x 3 columns]

#### Which stores in your assigned territories had at least one transaction with a sale amount over $1,000? How many such transactions did each store have?

In [26]:
Florida = StoreDetail[StoreDetail['State'] == 'Florida']
FloridaStores= StoreSales[(StoreSales['Store ID'] >= 719) & (StoreSales['Store ID'] <=729)]

# Merge datasets
FLTransData = (
    FloridaStores
    .merge(Products, on='Prod Num')
    .merge(ProductCat, on='CategoryID')
    .groupby(['Store ID', 'Category'], as_index=False)
    .agg({
        'Sale Amount': 'sum',              # total sales
        'Prod Num': 'count'               # transaction count
    })
    .rename(columns={'Prod Num': 'Transaction Count'})
)
FLTransData

    Store ID                  Category  Sale Amount  Transaction Count
0        719   Apparel and Merchandise    121101.44               3672
1        719              Art Supplies    128480.88               3872
2        719           Books (General)     20210.92                696
3        719   Stationery and Supplies     50638.94               4983
4        719  Technology & Accessories   1652690.55               3318
..       ...                       ...          ...                ...
61       729              Art Supplies    126099.27               3993
62       729           Books (General)     21738.92                756
63       729   Stationery and Supplies     54524.69               5236
64       729  Technology & Accessories   1527735.51               3479
65       729                 Textbooks    602711.45               3377

[66 rows x 4 columns]